global class OpptyLineItemsWapper
{
    
        public string Unique_ID='';
        public string OppID;
        public string ProductCode;
        public string ProductDesc;
        public string CurrencyType;
        public decimal UnitPrice;
        public decimal ListPrice;
        public decimal Quantity;
        public decimal Discount;
        public datetime LastModifiedDate;
        public datetime CreatedDate;
        public decimal Probability;
        public string Owner;
        public string Sales_Department;
        public date Required_Delivery_Date;
        public string StageName;
        public string distributor;
        public string NextStep;
        public boolean specialopportunity;
        
    }