@isTest(SeeAllData=true)
public class RSTest_RfSelfRegister {

/*public static testMethod void testControllers() {
 
    RSSiteController sitecontr = new RSSiteController();
    RSSiteRegisterConfirmController siteconfirmcontr = new RSSiteRegisterConfirmController();
    RSSiteRegisterController siteregcontr = new RSSiteRegisterController();
    
    sitecontr.username = 'test@salesforce.com';
    sitecontr.password = '123456';             
    
    //System.assertEquals(sitecontr.login(),null);  
    sitecontr.login();
    
    String AccountId = siteregcontr.getAccountOptions()[0].getValue();
    siteregcontr.firstname = 'testSelfRegUser';
    siteregcontr.lastname = 'testSelfRegUser';
    siteregcontr.email = 'testselfreguser@test.com';
    siteregcontr.selectedAccount = AccountId;
    siteregcontr.registerUser();
    //System.assert(siteregcontr.registerUser() == null); 
    
  
    
}
  */
}