/**
 * 
 * Class CDM_TEST_OppMatching_Custom
 * 
 * Unit test methods for the CDM_OppMatching_Custom custom Opportunity matching code.
 * Tests both the matching and unmatching methods asynchronous methods.
 */
@isTest
private class CDM_TEST_OppMatching_Custom {
    
    /* Create the basic test data for the configuration using TEST_TestUtils then create the test data for the custom code */
    @testSetup 
    public static void createClassTestData() {
        /* Configuration data */
        // Use the package data generation test method to set the configurations
       
        
        
}
}